### PR TITLE
Adds centralized events property (refactor). Fix #101.

### LINKED ISSUE #101: Suggestion: Error handling, events and code cleanup/refactors
I was testing my app against a down STS server and I did notice the error handling for `OidcSecurityService` is lacking. Some considerations:

- `OidcSecurityService.authorize()` doesn't provide any way for the caller to know if something wrong occurred. It has no return values and doesn't throw any exceptions.
  - The only thing it does in case of error is to call `oidcSecurityCommon.logError()`.
- `OidcSecurityService.handleError()` is never called.
  - Due to this, the `authConfiguration.forbidden_route` setting appears to be never used.
- `OidcSecurityService.runGetSigningKeys()` is never called.
  - Due to this, `OidcSecurityService.handleErrorGetSigningKeys()` is also never used.
- In several places we have the following pattern:
  ```javascript
  if (this.authConfiguration.trigger_authorization_result_event) {
      this.onAuthorizationResult.emit(AuthorizationResult.authorized);
  } else {
      this.router.navigate([this.authConfiguration.login_route]);
  }
  ```
  which is somewhat redundant, since the act of `.navigate()` to a certain route could be dispatched from a `onAuthorizationResult` (or similar) subscription.

Please take the above points with a grain of salt, since I'm very new to this code base and maybe I'm missing something. In this case, please enlighten me.

# Suggestions

To minimize breaking changes in the current code I propose the creation of a `.events()` property (very similar to [Angular Router Events](https://angular.io/api/router/Event)).

Suggested events: 

  - `AuthenticationStart`, `AuthenticationSuccess`, `AuthenticationError, AuthenticationRefresh, AuthenticationLogout` (main events)
    - `FetchConfigurationStart`, `FetchConfigurationSuccess`, `FetchConfigurationError` 
      - maps `getWellKnownEndpoints()`
    - `FetchKeysStart`, `FetchKeysSuccess`, `FetchKeysError`
      - maps `getSigningKeys()`
    - `FetchUserInfoStart`, `FetchUserInfoSuccess`, `FetchUserInfoError` 
      - maps `getIdentityUserData()`
    - `RefreshTokenStart`, `RefreshTokenSuccess`, `RefreshTokenError` 
      - maps the timer from `runTokenValidatation()`

This would be a central point for all event-related notifications and the user could subscribe to it to handle whatever he/she wishes. Initially this would be given just as an _additional_ way of reacting to events (i.e. it would not change any of current events/subscriptions). This way it would not require any breaking changes to the existing code (neither introduce any new bugs 😉 ).

Then, with these events in place, we could port independent parts of code (e.g. logging, route navigation, core functionality) from the current state to _subscriptions_ of these events.

IMO this could bring large benefits to the code readability and maintenance.

And, of course, I'm willing to make PRs for all this, if agreed. 😄 

Best regards!

### PR DESCRIPTION
**Pull request by fdcastel**
Similar to #107 but for current master.

- Also adds `RefreshTokenExpired` as discussed in #79.

### CODE REVIEW

**Comment by damienbod** [comment]
@fdcastel Can you fix? I plan to test and merge this on Friday.

Greetings Damien

**Comment by fdcastel** [comment]
Sorry, Damien. I believe I've been missing something. Fix what? :')

**Comment by damienbod** [comment]
hi @fdcastel 

ERROR in ./src/services/oidc.security.service.ts

(55,43): error TS2322: Type 'Subject<OidcEvent>' is not assignable to type 'Observable<OidcEvent>'.

**Comment by fdcastel** [comment]
​DOH! Sorry, Damien. ​My `npm run build` was running fine. But now I ran a `npm install` and I did see the problem... I was building with outdated packages. 🤦‍♂️ 

Fixed now.

**Comment by damienbod** [comment]
@fdcastel thanks looks good. @FabianGosebrink @robisim74 

I'll test and merge the branch from @robisim74 first, then this one.

**Comment by vorotech** [comment]
Voting for this PR as I'm trying to integrate this library with Angular Redux ([@ngrx](http://ngrx.github.io/)) style app.

**Comment by starquake** [comment]
Any plans on merging this?

**Comment by shambarick** [comment]
Any news about this PR? It would be great to have these events.

**Comment by profet23** [comment]
Are there specific events people are looking for?  This PR hasn't aged well in the relation to the rest of the project. Many of the events are now present in other forms.

**Comment by Booster2ooo** [comment]
Yes, I think some people are still looking for a way to manage token expiracy (e.g.: https://github.com/damienbod/angular-auth-oidc-client/issues/79 )

**Comment by profet23** [comment]
> Yes, I think some people are still looking for a way to manage token expiracy (e.g.: #79 )

@Booster2ooo 

If by "manage" you mean receive notification that an expiration is about to occur...  that is easily doable with the current API:

```typescript
        this.oidcSecurityService.getIsAuthorized().pipe(
            filter((isAuthorized) => isAuthorized),
            map(() => this.oidcSecurityService.getPayloadFromIdToken()),
            pluck('exp'),
            delayWhen((exp: number) => {
                const date = new Date(0); // The 0 here is the key, which sets the date to the epoch
                date.setUTCSeconds(exp);

                const timeToExpiration = date.valueOf() - (new Date().valueOf());
                const timeToNotification = timeToExpiration - (60 * 1000)  //1 minute before expiration

                return timer(timeToNotification);
            }),
            filter((exp) => {
                let payload = this.oidcSecurityService.getPayloadFromIdToken();
                return exp === payload.exp;
            })
        ).subscribe(() => {
            //do something when token is 1 minute from expiration
        });
```

Is this enough?  Does this need to be built into the library itself?

@damienbod

**Comment by damienbod** [comment]
@profet23 thanks for this. I don't see the need for this in the lib, we already have the silent renew.

**Comment by profet23** [comment]
@damienbod maybe we close this PR then? I don't think its relevant anymore.

**Pull request closed without merging**
