### PR TITLE
#552 adds ignore nonce after refresh config paramater with implementa…

### PR DESCRIPTION
**Pull request by remkoboschker**
…tion and unit test

### CODE REVIEW

**Comment by remkoboschker** [comment]
There appears to be an issue with installing chrome
```
apt-get install failed

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install google-chrome-stable" failed and exited with 100 during .
```

**Comment by damienbod** [comment]
@remkoboschker Thanks, will look at this hopefully tomorrow, having a busy week...

**Comment by FabianGosebrink** [comment]
Fixed on master, can you merge master in your PR again? Build should run then. Thanks.

**Comment by damienbod** [comment]
CAn you update your branch to solve the conflicts? The linting seems to have caused this

**Comment by damienbod** [comment]
thanks, merging now, and will do some manually testing before I create a new npm package

Greetings Damien

**Pull request merged**
