### PR TITLE
fix: make package with HMR

### PR DESCRIPTION
**Pull request by yelhouti**
fixes: #1658

### CODE REVIEW

**Comment by FabianGosebrink** [comment]
LGTM, we have to fix the linting, and then I think we are good to go. Thanks!

**Comment by yelhouti** [comment]
@FabianGosebrink as soon as I have a little bit of time, thanks for the quick feedback

**Comment by FabianGosebrink** [comment]
Whenever you are ready! Thank you for the PR!

**Comment by yelhouti** [comment]
@FabianGosebrink sorry some changes didn't get committed yesterday, could you please trigger again

**Comment by yelhouti** [comment]
@FabianGosebrink I ma really sorry, I was checking my changes here, and found that I commited a compiled version of the project by mistake.
Now this permanently cloned even if you rebase my change.
Git tree must be cleaned.
Whether you decide to fix this or not, please make that the build is moved automatically to a gitignored folder, to avoid similar issues

**Pull request merged**
