### PR TITLE
Use window object safely by injecting document

### PR DESCRIPTION
**Pull request by FabianGosebrink**

### CODE REVIEW

**Comment by FabianGosebrink** [comment]
@GabrielGil please give feedback if this is okay for you. @damienbod maybe you can test.

**Comment by damienbod** [comment]
I do some testing.

**Comment by FabianGosebrink** [comment]
I will update the code coverage tomorrow

**Comment by damienbod** [comment]
Manual teats ok tested in Chrome, Edge and Firefox

**Comment by damienbod** [comment]
@GabrielGil @FabianGosebrink Thanks for this LGTM

Ready to merge and release.

version  11.3.0

**Pull request merged**
