### PR TITLE
fix concurrent issue with renew and normal code flow

### PR DESCRIPTION
**Pull request by Tom-V**
Hi,

I tried to fix this issue myself: https://github.com/damienbod/angular-auth-oidc-client/issues/1479
I tested it and it looks like it's behaving like it should. 

Can you please check the pull request and guide me to improve it so it can be merged? 

Kind regards

### CODE REVIEW

**Comment by Tom-V** [comment]
I suppose those errors shouldn't be by my PR as I don't change any dependency, if I see that wrong, please let me know.

**Comment by FabianGosebrink** [comment]
I will check the dependency issue on another branch...

**Comment by FabianGosebrink** [comment]
If you merge main again into your branch, the dependency problems should be resolved.

**Comment by Tom-V** [comment]
I merged the branch, with approval it will run the workflow again

**Comment by FabianGosebrink** [comment]
Looks good, doesn't it? :) @damienbod can you please verify if this is correct behavior? Code lgtm. Thanks for this PR!!!

**Comment by damienbod** [comment]
LGTM

**Comment by damienbod** [comment]
thanks!

**Pull request merged**
