### PR TITLE
refactor: replace any types

### PR DESCRIPTION
**Pull request by timdeschryver**
This PR updates some `any` types to its runtime type or to `unknown` for errors.
Some tests are also updates to replace a "magic string" that contains `any` within the string.

### CODE REVIEW

**Comment by FabianGosebrink** [comment]
Nice, thanks!

**Comment by FabianGosebrink** [comment]
Are you finished and we can merge?

**Comment by timdeschryver** [comment]
@FabianGosebrink there are still some `any`'s left, but I already wanted to create this PR (and merge it) because I will be busy the next days.
One side note that I have is that this can result in a breaking change if some of these types are exposed and a user passes an invalid type.

**Comment by FabianGosebrink** [comment]
Let us merge and then see on main and the samples how it goes.

**Comment by FabianGosebrink** [comment]
Thanks!

**Pull request merged**
