### PR TITLE
Expose PopupService as public #1199

### PR DESCRIPTION
**Pull request by normandjulian**
I'm sorry for the last PR, I exposed the wrong service `PopUpLoginService` instead of `PopUpService` ...

### CODE REVIEW

**Comment by FabianGosebrink** [comment]
Hey, thanks, do we need to expose the `PopupLoginService ` then?

**Comment by normandjulian** [comment]
Not really you're right, I'll update my PR

**Comment by FabianGosebrink** [comment]
Can you please update this PR accordingly, that we can merge? Thanks.

**Comment by normandjulian** [comment]
It should be good now ! Thank you.

**Pull request merged**
