### PR TITLE
Added ability to use Custom Parameters when calling ForceRefreshSession

### PR DESCRIPTION
**Pull request by juanp3053**

### CODE REVIEW

**Comment by damienbod** [comment]
@juanp3053 looks good, thanks. Can you fix the linting and the tests?

Greetings Damien

**Comment by juanp3053** [comment]
@damienbod Done! thanks.

**Comment by juanp3053** [comment]
While I Had the PR open, I went ahead and fixed issue in #909 . Thanks @damienbod

**Comment by FabianGosebrink** [comment]
@damienbod @juanp3053 LGTM. Thank you very much!

**Comment by damienbod** [comment]
@juanp3053 thanks for the PR. This will be relesed in version 11.4.3

**Pull request merged**
