### PR TITLE
Implemented CanActivateChild interface for auto-login guards

### PR DESCRIPTION
**Pull request by marklagendijk**
With this the guards can be used as argument for `canActivateChild`, so that the guard will be executed when loading any child route:
```ts
export const appRoutes: Routes = [
  {
    path: '', canActivateChild: [AutoLoginAllRoutesGuard], children: [
      {path: '', component: HomeComponent, pathMatch: 'full'},
      {path: 'fetch-data', component: FetchDataComponent},
    ],
  },
  {path: 'unauthorized', component: UnauthorizedComponent, pathMatch: 'full'},
]
```

### CODE REVIEW

**Comment by marklagendijk** [comment]
Note: even though it is called `CanActivateChild` it is actually called whenever any descendant is activated, so it also works for deeply nested routes.

**Comment by FabianGosebrink** [comment]
Thanks for this. We will review and merge in the next days! Thanks! Much appreciated.

**Comment by FabianGosebrink** [comment]
Can you take a look at the conflicts here? Thanks :)

**Comment by marklagendijk** [comment]
@FabianGosebrink the conflict is resolved.

**Comment by FabianGosebrink** [comment]
Wonderful, thanks. Will be in the next release.

**Comment by jacksoncastro** [comment]
> Wonderful, thanks. Will be in the next release.

When will the next release be?

**Comment by FabianGosebrink** [comment]
@damienbod is on holiday right now and we have to drive some tests. So I think at the end of next week somewhat around this.

**Pull request merged**
