### PR TITLE
Included authOptions in createBodyForParCodeFlowRequest - url.service.ts

### PR DESCRIPTION
**Pull request by clempire1**

### CODE REVIEW

**Comment by clempire1** [comment]
Currently the AuthOptions in the authorise method is not allowing us to override the redirectUrl properly, with these changes, it is possible.

**Comment by FabianGosebrink** [comment]
Nice, thanks! LGTM, can we fix the testing?

**Comment by clempire1** [comment]
> Nice, thanks! LGTM, can we fix the testing?

I just resolved the testcases! Forgot to run the tests, my bad :)

**Comment by FabianGosebrink** [comment]
All good, happens to me every time :)

**Comment by clempire1** [comment]
After the pull request is merged, can you publish this bug fix on NPM?

**Comment by FabianGosebrink** [comment]
@damienbod ?

**Pull request merged**
