### PR TITLE
Fix URLSearchParams: #113

### PR DESCRIPTION
**Pull request by robisim74**

### CODE REVIEW

**Comment by robisim74** [comment]
WIP

**Comment by robisim74** [comment]
@damienbod At the moment, the library doen't work in IE and Edge. When you moved to HttpClient, `URLSearchParams` still worked because there is a JavaScript interface `URLSearchParams`: but it is not supported by all browsers: https://developer.mozilla.org/it/docs/Web/API/URLSearchParams.

I moved to `HttpParams`, but I found another problem (Angular bug): https://github.com/angular/angular/issues/18261, still opened in v5. So as suggested here: https://github.com/angular/angular/issues/18261#issuecomment-338354119, I created a custom encoder with the default `encodeURIComponent` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent

It seems works, but it is important that you do other tests.

**Comment by damienbod** [comment]
@robisim74 thanks, I'll merge this first then with the doc PR.

**Comment by damienbod** [comment]
tested:

Chrome:

t4=ABC%20abc%20123&t3=%23&t2=-_.!~*()&t1=;,%2F%3F%3A@%26%3D%2B$

Edge:

t4=ABC%20abc%20123&t3=%23&t2=-_.!~*()&t1=;,%2F%3F%3A@%26%3D%2B$

IE:

t4=ABC%20abc%20123&t3=%23&t2=-_.!~*()&t1=;,%2F%3F%3A@%26%3D%2B$

Firefox:

t4=ABC%20abc%20123&t3=%23&t2=-_.!~*()&t1=;,%2F%3F%3A@%26%3D%2B$

thanks, also added a test

**Pull request merged**
