### PR TITLE
Update existing-iframe.service.ts

### PR DESCRIPTION
**Pull request by MrGrabazu**
It raise an error on server side rendering because it try to call window despite the fact that it is not existing on server side.

### CODE REVIEW

**Comment by profet23** [comment]
While this does fix the error, I think we probably want to disable `silent_renew` and `start_checksession` for server platforms. Since those two operations both require iframes. This would prevent other odd interactions.

Some unit tests wouldn't hurt either.

**Comment by profet23** [comment]
There might also be an argument for saying that the developer should be disabling both the silent renew and check session in their configuration when running on the server. 

Would be curious what @damienbod and @FabianGosebrink think.

**Comment by damienbod** [comment]
@profet23  Yes, when running on the server, the silent renew and check session should be not on.  Just wondering what is the use case for using SSR? I never use this.

**Comment by profet23** [comment]
@damienbod i never use it either. To me it doesn't make sense to use it for client side authorized apps. It may be useful if you want to render unauthorized pages. But yes. I would tend to a "won't fix" and just tell the user to make sure to disable silent renew and check session for SSR.

**Comment by FabianGosebrink** [comment]
I do not use SSR as well but I do see usecases. However we should make it configurable imho.

**Comment by robisim74** [comment]
@damienbod @profet23  @FabianGosebrink SSR does not happen at runtime. With SSR the app _is rendered before_ it is executed, so it is not possible to tell the user to disable an option. The only way is that already followed by this library, and correctly implemented by this pr: use `isPlatformBrowser`

**Comment by profet23** [comment]
@robisim74 what i mean is that the configuration code should utilize `isPlatformBrowser` to determine the correct configuration for the platform.

**Comment by robisim74** [comment]
Ok, the result will be the same: the only important thing is that the code that contains _window_ or manipulates the DOM it is not executed during server-side rendering, and that for this purpose   `isPlatformBrowser` is used.

**Comment by profet23** [comment]
Right. I just think it might be a code "smell" to have the library simply do nothing when it is asked to do a silent renew or a check session routine.

I think I'm of the opinion (although I could be persuaded) that the library is functioning as intended, but the developer has configured it incorrectly for their target platform when its rendering on the server.

**Comment by robisim74** [comment]
I see. But usually that is not left to the developer, but to libraries in order to avoid these problems.

**Comment by profet23** [comment]
If that's convention. I'm fine with it. But I'm not a fan of the approach used in this pull request. 

I think the `AuthConfiguration` class should override `silent_renew` and `start_checksession` to always be false when not running in the browser. 

Again... i could be probably be convinced otherwise.

**Comment by profet23** [comment]
That can go away if we move the check to two properties in the `AuthConfiguration` class.

As it will hit this: https://github.com/damienbod/angular-auth-oidc-client/blob/a1700be90e0f20644e8e3f89f6e2b4cbacd9e5d5/src/services/oidc.security.service.ts#L173

**Comment by profet23** [comment]
@robisim74   Please see my proposal for this here:  #341

**Comment by robisim74** [comment]
Because you merged #341, it should not be necessary.

**Comment by profet23** [comment]
Once #341 is tested/approved we can probably abandon/close this PR.

**Comment by damienbod** [comment]
@MrGrabazu The feature added in this PR is now included in version 8.0.2. #341  Thanks you very much for this PR.

**Pull request closed without merging**
