### PR TITLE
Another try to compose authorization url.

### PR DESCRIPTION
**Pull request by HWouters**
Could you have a look to this?

I'm now using URLSearchParams from Angular to prevent IE10 issues.

Should handle custom parameters properly now.

### CODE REVIEW

**Comment by damienbod** [comment]
Hi @HWouters 
Testing now, will create a npm tomorrow, after I test in the different browsers

Thanks Damien

**Comment by damienbod** [comment]
Released in version 1.3.6, tested in Edge, Firefox and Chrome

Do you have  an example of Azure Active Directory B2C? Would be great.

Thanks for your PR.

**Comment by HWouters** [comment]
I'm checking out Azure B2C for my application at the moment. If everything works well I'll create an sample app.

**Comment by HWouters** [comment]
I have created a sample application at: [ad-b2c-oidc-angular](https://github.com/HWouters/ad-b2c-oidc-angular)
Only signup/signin is working at the moment. Signout requires #62

**Pull request merged**
