### PR TITLE
Fixed Bug were Dynamic Custom Request Parameters are forgotten after first login or forceRefreshSession when doing a silent renew/refresh

### PR DESCRIPTION
**Pull request by juanp3053**
Bug reports: #911 #912 
I have fixed the tests and linting, please let me know if need to change anything else.
Thanks

### CODE REVIEW

**Comment by damienbod** [comment]
LGTM

**Review by FabianGosebrink — APPROVED** [review]

**Comment by damienbod** [comment]
Hi @juanp3053

I am testing your PR and it breaks the token endpoint request. Moved your changes to a branch:

https://github.com/damienbod/angular-auth-oidc-client/tree/juanp3053/Dynamic-Custom-Request

Need to find out why this has problems before we can merge.

Greetings Damien

**Comment by juanp3053** [comment]
@damienbod I didn't get a notification on this. I will take a look a try testing more. I didn't have any issues but I mostly did my testing using PKCE with refresh tokens

**Comment by FabianGosebrink** [comment]
Hey @juanp3053 , easy, no worries. We are thankful for the PR. We would be glad you would fi then we can test again and then we will get this thing going :) Thanks again. 👌

**Pull request merged**
