### PR TITLE
[Question]: Move Http Interceptor into its own page #1674

### PR DESCRIPTION
**Pull request by FabianGosebrink**
#1674

### CODE REVIEW

**Comment by FabianGosebrink** [comment]
@timdeschryver would you like to review

**Review by timdeschryver — APPROVED** [review]
It's great, thanks!

A few nits (I can't comment in the file because the lines are untouched):

- `You can configure the routes you want to send a token with in the configuration` should be `You can configure the routes you want to send a token within the configuration`

- `The lib provides an own interceptor implementation which` should be `The lib provides its own interceptor implementation which`

**Comment by FabianGosebrink** [comment]
Pushed. With your OK I'll merge.

**Comment by timdeschryver** [comment]
Hereby I give you my formal OK 😁

**Pull request merged**
