### PR TITLE
Popup: calculate top and left position to center the window. Export more services to public API. Add AutoRedirectRoutesGuard

### PR DESCRIPTION
**Pull request by linjie997**
1. Popup: Calculate top and left positions to center the popup window

2. Export to public API: AutoLoginService, AuthStateService, LoginService, ConfigurationProvider.
Exporting such services to public API, can allow the creation of custom RoutesGuard (other than AutoLoginAllRoutesGuard and AutoLoginPartialRoutesGuard).

3. Add AutoRedirectRoutesGuard: Basically it's a copy of AutoLoginPartialRoutesGuard but does not try to login and only saves the requested route.
This may be useful when we want to conditionally trigger the login only later after some checks.

### CODE REVIEW

**Comment by linjie997** [comment]
Export to public API: AutoLoginService, AuthStateService, LoginService,
ConfigurationProvider.
Exporting such services to public API, can allow the creation of custom
RoutesGuard (other than AutoLoginAllRoutesGuard and
AutoLoginPartialRoutesGuard).

**Comment by linjie997** [comment]
Sorry for the mess, I will use different branches for each pull request next time.

**Comment by FabianGosebrink** [comment]
We have to be careful to what we expose. We can not expose everything, therefore we have the facade we are providing. Exposing everything would open the door for uncontrolled usecases. Can we split this up? Make on PR for the Popup changes. Then we can merge this. One for the rename then.

**Comment by linjie997** [comment]
Sure, will split up.

**Pull request closed without merging**
