### PR TITLE
implementing getter and setters on oidcsecuritycommon

### LINKED ISSUE #111: OidcSecurityCommon should be strongly typed
OidcSecurityCommon should use getters and setters in order to ensure type safety.

### PR DESCRIPTION
**Pull request by MovGP0**
fixes #111 implemented strongly typed getters and setters on `oidc.security.common`

### CODE REVIEW

**Comment by damienbod** [comment]
@MovGP0 thanks, I 'll go through this as soon as possible.

**Comment by damienbod** [comment]
@MovGP0 could you update your branch, had to merge a urlparams bug fix which has conflicts to your PR

Greetings Damien

**Comment by MovGP0** [comment]
the version is now rebased

**Comment by damienbod** [comment]
@MovGP0 thanks`! nice improvement, tested

Greetings Damien

**Pull request merged**
