### PR TITLE
Fabiangosebrink/adding abstract services

### PR DESCRIPTION
**Pull request by FabianGosebrink**
#1416

### CODE REVIEW

**Comment by FabianGosebrink** [comment]
@timdeschryver if you have the time to review, feel free :)

**Comment by timdeschryver** [comment]
@FabianGosebrink I'll make some time for this next week.

**Review by timdeschryver — COMMENTED** [review]
I think that a couple of changes already were pushed to `main` (ad4b090ddd950db318c2b7ffb8831be633f602d4).

This PR looks good to me and I also like the changes to the storage, this makes things consistent and flexible.  
But I had something else in mind for the logger.

```diff
import { Injectable } from '@angular/core';
import { OpenIdConfiguration } from '../config/openid-configuration';
import { AbstractLoggerService } from './abstract-logger.service';
import { LogLevel } from './log-level';

@Injectable()
export class LoggerService  {

  constructor(private log: AbstractLoggerService) {}

  logError(configuration: OpenIdConfiguration, message: any, ...args: any[]): void {
    if (this.loggingIsTurnedOff(configuration)) {
      return;
    }

    const { configId } = configuration;

    if (!!args && !!args.length) {
-      console.error(`[ERROR] ${configId} - ${message}`, ...args);
+      this.log.logError(`[ERROR] ${configId} - ${message}`, ...args);
    } else {
-      console.error(`[ERROR] ${configId} - ${message}`);
+      this.log.logError(`[ERROR] ${configId} - ${message}`);
    }
  }

  logWarning(configuration: OpenIdConfiguration, message: any, ...args: any[]): void {
    if (!this.logLevelIsSet(configuration)) {
      return;
    }

    if (this.loggingIsTurnedOff(configuration)) {
      return;
    }

    if (!this.currentLogLevelIsEqualOrSmallerThan(configuration, LogLevel.Warn)) {
      return;
    }

    const { configId } = configuration;

    if (!!args && !!args.length) {
-      console.warn(`[WARN] ${configId} - ${message}`, ...args);
+      this.log.logWarning(`[WARN] ${configId} - ${message}`, ...args);
    } else {
-      console.warn(`[WARN] ${configId} - ${message}`);
+      this.log.logWarning(`[WARN] ${configId} - ${message}`);
    }
  }

  logDebug(configuration: OpenIdConfiguration, message: any, ...args: any[]): void {
    if (!this.logLevelIsSet(configuration)) {
      return;
    }

    if (this.loggingIsTurnedOff(configuration)) {
      return;
    }

    if (!this.currentLogLevelIsEqualOrSmallerThan(configuration, LogLevel.Debug)) {
      return;
    }

    const { configId } = configuration;

    if (!!args && !!args.length) {
-      console.log(`[DEBUG] ${configId} - ${message}`, ...args);
+      this.log.logDebug(`[DEBUG] ${configId} - ${message}`, ...args);
    } else {
-      console.log(`[DEBUG] ${configId} - ${message}`);
+      this.log.logDebug(`[DEBUG] ${configId} - ${message}`);
    }
  }

  private currentLogLevelIsEqualOrSmallerThan(configuration: OpenIdConfiguration, logLevelToCompare: LogLevel): boolean {
    const { logLevel } = configuration || {};

    return logLevel <= logLevelToCompare;
  }

  private logLevelIsSet(configuration: OpenIdConfiguration): boolean {
    const { logLevel } = configuration || {};

    if (logLevel === null) {
      return false;
    }

    if (logLevel === undefined) {
      return false;
    }

    return true;
  }

  private loggingIsTurnedOff(configuration: OpenIdConfiguration): boolean {
    const { logLevel } = configuration || {};

    return logLevel === LogLevel.None;
  }
}
```

The reasoning behind this, is that the logger service already contains some useful checks whether that it should log or not, and these are fine. From a consumers view, I just want to use another logger implementation than `console.log`.

**Comment by FabianGosebrink** [comment]
I like that idea. That of course makes sense. With this, the user can use the checks which are already there. Will implement this and push. IDK why some things are already on main tbh...

**Review by timdeschryver — COMMENTED** [review]
@FabianGosebrink Exactly, this is perfect! 🤩
Thanks for implementing this so quickly.

**Review by timdeschryver — APPROVED** [review]

**Comment by FabianGosebrink** [comment]
Thank you for providing such a valuable and good feedback so quickly! Thanks :)

**Pull request merged**
