### PR TITLE
Popup: calculate top and left position to center the window.

### PR DESCRIPTION
**Pull request by linjie997**

### CODE REVIEW

**Comment by FabianGosebrink** [comment]
Please fix tests. Thanks!

**Comment by damienbod** [comment]
@linjie997 Thanks for the PR!

Could you fix the unit tests and we can merge?

Greetings Damien

**Comment by linjie997** [comment]
The tests are fixed.
The build and deployment are stuck because of the azure api token, can we skip that?

**Comment by FabianGosebrink** [comment]
Yes that is fine. We have to activate the secret sharing.

**Pull request merged**
