### PR TITLE
Added fix overwriting param

### PR DESCRIPTION
**Pull request by FabianGosebrink**
#1192

### CODE REVIEW

**Review by pfeigl — COMMENTED** [review]
Did you intentionally only fix the prompt now and not also all the other appends (scope, nonce, hd)?

**Comment by FabianGosebrink** [comment]
I have to speak to @damienbod or look in the docs if overwriting the params like `nonce`, `scope` etc is even allowed.

**Comment by pfeigl** [comment]
Scope might even be a special case in terms of it beeing kind of list already (space delimited string). Here overwriting probably makes no sense here, however having two scope parameters defined isn't better IMHO.

Perhaps your approach is best by fixing this specific issue, because prompt is the only `customParamsAuthRequest` parameter which is actually used out there right now.

**Comment by FabianGosebrink** [comment]
Have to fix the coverage. @damienbod is in vacation until next week, we will verify this and then merge. Stay tuned here if you want. :)

**Comment by damienbod** [comment]
You could also overwrite the scope maybe?

**Pull request merged**
