### PR TITLE
Removed AuthorizedState enum

### PR DESCRIPTION
**Pull request by JerrettDavis**
`AuthorizedState` should only ever be true or false, I have removed the `AuthorizedState` enum per issue #755.

### CODE REVIEW

**Comment by inloox-dev** [comment]
Wir erleichtern Ihnen den Einstieg mit InLoox Planungsvorlagen und stellen die Offline-Funktion detailliert vor.
InLoox Fehler wurde zur Nachverfolgung erstellt
[https://gallery.mailchimp.com/6fb276e204c3e429e34db0e30/images/43782466-0ad5-4511-953f-282e94d647e5.jpg] <https://www.inloox.de/?link=9671>
Guten Tag,


Fehler 25297 wurde zur Nachverfolgung erstellt

Titel: [damienbod/angular-auth-oidc-client] Removed AuthorizedState enum (#1062)

Herzliche Grüße
Dein InLoox Dev-Team

Fehler anzeigen<https://inloox.visualstudio.com//InLoox%20PM/_workitems/edit/25297>
FOLGEN SIE UNS!
[Twitter]<https://twitter.com/inloox_gmbh>
[Facebook]<https://www.facebook.com/InLoox>
[Newsletter-Anmeldung]<https://www.inloox.de/about-us/contact-us/?mode=newsletter>
[Google Plus]<https://plus.google.com/+InlooxDe/posts>
[YouTube]<https://www.youtube.com/user/InLoox>
[InLoox auf Instagram]<https://www.instagram.com/inlooxgmbh/>
Impressum<https://www.inloox.de/impressum/>                             Datenschutzbestimmungen<https://www.inloox.de/datenschutzbestimmungen/>
Copyright © 2019 InLoox GmbH, All rights reserved.

________________________________
From: JD Davis ***@***.***>
Sent: Saturday, April 24, 2021 10:21:39 PM
To: damienbod/angular-auth-oidc-client ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [damienbod/angular-auth-oidc-client] Removed AuthorizedState enum (#1062)


AuthorizedState should only ever be true or false, I have removed the AuthorizedState enum per issue #755<https://github.com/damienbod/angular-auth-oidc-client/issues/755>.

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/damienbod/angular-auth-oidc-client/pull/1062

Commit Summary

  *   Removed AuthorizedState enum per issue #755

File Changes

  *   M .gitignore<https://github.com/damienbod/angular-auth-oidc-client/pull/1062/files#diff-bc37d034bad564583790a46f19d807abfe519c5671395fd494d8cce506c42947> (2)
  *   M projects/angular-auth-oidc-client/src/lib/authState/authorization-result.ts<https://github.com/damienbod/angular-auth-oidc-client/pull/1062/files#diff-ca3e7a820fffca9bc7e01b18c8da20318f8451a679681d1bd4d11bf6ab72f013> (3)
  *   D projects/angular-auth-oidc-client/src/lib/authState/authorized-state.ts<https://github.com/damienbod/angular-auth-oidc-client/pull/1062/files#diff-0584d8eed90b80d4a95b4d713250a0bc52fdbaf7e124afb01030a90f5578a28f> (6)
  *   M projects/angular-auth-oidc-client/src/lib/flows/callback-handling/history-jwt-keys-callback-handler.service.ts<https://github.com/damienbod/angular-auth-oidc-client/pull/1062/files#diff-7b6863ae6d20a8f207c62ccd78a1976a8eff9de4c3a0209a949c0f5f9241b196> (3)
  *   M projects/angular-auth-oidc-client/src/lib/flows/callback-handling/state-validation-callback-handler.service.spec.ts<https://github.com/damienbod/angular-auth-oidc-client/pull/1062/files#diff-ee6a79dc91631f4e8eb0406e8b3b6fb9a529549dcfdf358a191851cc2af4229e> (3)
  *   M projects/angular-auth-oidc-client/src/lib/flows/callback-handling/state-validation-callback-handler.service.ts<https://github.com/damienbod/angular-auth-oidc-client/pull/1062/files#diff-1bd8843423945116640c92e7f69abbae705d20a0b00f98d9b816d933ef7466b3> (3)
  *   M projects/angular-auth-oidc-client/src/lib/flows/callback-handling/user-callback-handler.service.ts<https://github.com/damienbod/angular-auth-oidc-client/pull/1062/files#diff-3344c18d1a45182fc4e5c324a24ba6305292ee396ae31509273beb1247d77e5c> (5)
  *   M projects/angular-auth-oidc-client/src/lib/iframe/silent-renew.service.ts<https://github.com/damienbod/angular-auth-oidc-client/pull/1062/files#diff-baf477408de109a8662283ff8cbebfb09f80a959aac39ef1a0de0510386055ab> (3)

Patch Links:

  *   https://github.com/damienbod/angular-auth-oidc-client/pull/1062.patch
  *   https://github.com/damienbod/angular-auth-oidc-client/pull/1062.diff

-

**Comment by JerrettDavis** [comment]
It seems the app uses "authorized" and "authenticated" nearly interchangeably. I initially authored this with `isAuthorized`, but I believe `isAuthenticated` is more accurate, and it better adheres to similarly named responses in other areas. 

On that note, is there any reason why "authorized" is used in place of "authenticated" in other places in the application? To my knowledge, [these](https://www.okta.com/identity-101/authentication-vs-authorization/) are [different](https://authress.io/knowledge-base/authn-vs-authz) things.

**Comment by damienbod** [comment]
@JerrettDavis LGTM

**Comment by FabianGosebrink** [comment]
Looks good to me as well. I am sure @damienbod will answer your questions. Could you in the meantime

1. Target the V12-Branch to merge this PR into [releaseV12-WIP](https://github.com/damienbod/angular-auth-oidc-client/tree/releaseV12-WIP)
2. Add a migration chapter to the migration doc. There is a file already in the V12-Branch. There a new chapter can be added. [Migration V11 to V 12](https://github.com/damienbod/angular-auth-oidc-client/blob/releaseV12-WIP/docs/migration.md#version-11-to-version-12)
3. 
Thanks!

**Comment by JerrettDavis** [comment]
I have corrected the target branch, merged the`releaseV12-WIP` branch into mine, and updated the documentation accordingly. Please let me know if any other changes are needed.

Thanks!

**Pull request merged**
