### PR TITLE
Adds centralized events property. Fix #101.

### LINKED ISSUE #101: Suggestion: Error handling, events and code cleanup/refactors
I was testing my app against a down STS server and I did notice the error handling for `OidcSecurityService` is lacking. Some considerations:

- `OidcSecurityService.authorize()` doesn't provide any way for the caller to know if something wrong occurred. It has no return values and doesn't throw any exceptions.
  - The only thing it does in case of error is to call `oidcSecurityCommon.logError()`.
- `OidcSecurityService.handleError()` is never called.
  - Due to this, the `authConfiguration.forbidden_route` setting appears to be never used.
- `OidcSecurityService.runGetSigningKeys()` is never called.
  - Due to this, `OidcSecurityService.handleErrorGetSigningKeys()` is also never used.
- In several places we have the following pattern:
  ```javascript
  if (this.authConfiguration.trigger_authorization_result_event) {
      this.onAuthorizationResult.emit(AuthorizationResult.authorized);
  } else {
      this.router.navigate([this.authConfiguration.login_route]);
  }
  ```
  which is somewhat redundant, since the act of `.navigate()` to a certain route could be dispatched from a `onAuthorizationResult` (or similar) subscription.

Please take the above points with a grain of salt, since I'm very new to this code base and maybe I'm missing something. In this case, please enlighten me.

# Suggestions

To minimize breaking changes in the current code I propose the creation of a `.events()` property (very similar to [Angular Router Events](https://angular.io/api/router/Event)).

Suggested events: 

  - `AuthenticationStart`, `AuthenticationSuccess`, `AuthenticationError, AuthenticationRefresh, AuthenticationLogout` (main events)
    - `FetchConfigurationStart`, `FetchConfigurationSuccess`, `FetchConfigurationError` 
      - maps `getWellKnownEndpoints()`
    - `FetchKeysStart`, `FetchKeysSuccess`, `FetchKeysError`
      - maps `getSigningKeys()`
    - `FetchUserInfoStart`, `FetchUserInfoSuccess`, `FetchUserInfoError` 
      - maps `getIdentityUserData()`
    - `RefreshTokenStart`, `RefreshTokenSuccess`, `RefreshTokenError` 
      - maps the timer from `runTokenValidatation()`

This would be a central point for all event-related notifications and the user could subscribe to it to handle whatever he/she wishes. Initially this would be given just as an _additional_ way of reacting to events (i.e. it would not change any of current events/subscriptions). This way it would not require any breaking changes to the existing code (neither introduce any new bugs 😉 ).

Then, with these events in place, we could port independent parts of code (e.g. logging, route navigation, core functionality) from the current state to _subscriptions_ of these events.

IMO this could bring large benefits to the code readability and maintenance.

And, of course, I'm willing to make PRs for all this, if agreed. 😄 

Best regards!

### PR DESCRIPTION
**Pull request by fdcastel**
- Adds events property and typed events.
- Removes _isAuthorizedValue (redundant, BehaviorSubject already stores the last value)
- Removes lastUserData and onUserDataChanged() (not needed anymore)
- Minor refactors and code formatting
- Updates package-lock.json

P.S.: Please review "ToDo:" and "Warning:" comments in the code.

### CODE REVIEW

**Comment by damienbod** [comment]
@fdcastel thanks a million. Looks good, a lot to test here, as the lib has no auto tests, I do this manaully. I'll plan to complete this at the weekend. 

1 question? Should we document the events in the  API doc?

**Comment by fdcastel** [comment]
> Should we document the events in the API doc?

Surely! I was just waiting for your feedback about the events I implemented (are they good? something missing? something to remove? What about the parameters passed in each one?).

As proposed in #101 I looked to make this PR additive-only, with no breaking changes at all.

**Comment by damienbod** [comment]
I think the events are good. @robisim74 @CesarD

**Comment by robisim74** [comment]
@damienbod @fdcastel I'm not understanding what's going on here: ok for the events, but also this pr has a lot of strange changes.

For example, @fdcastel you are now removing `onUserDataChanged` method, but this method has been added by you 6 days ago with this pr: https://github.com/damienbod/angular-auth-oidc-client/pull/99/files

I think prs should treat one thing at a time, or at least have different commits: you can not test so many changes.

**Comment by CesarD** [comment]
Thanks for tagging me, @damienbod 
Looks good so far (though I'm not having a lot of time to look into the very detail).

My main concern when I created #79 was about having some events like "AccessTokenExpiring" or "AccessTokenExpired", which should trigger when such scenarios are occurring (either during the execution of the app or when loading it). This way, I can hook them from the app to make redirects or showing messages to the users (in the case silent refresh was not possible for any reason). If I cannot detect that the access token expired, I'd be more easily prone to make an unauthorized request to the server without prior notice.

**Comment by fdcastel** [comment]
@robisim74 I fully agree with you.

I'm sorry for the lack of time to polish the PR. I just wrote it in a few hours I had available and send it for feedback. We don't need to merge it as it stands. Also, I did not documented the changes at all (apart from the short commit description, which I assumed was enough).

About the event `onUserDataChanged`: I removed it **exactly** because I just had created it. When Damien brought back `_isAuthorized` (which I deemed unnecessary) from #99 I started to understand better some concepts and changed my mind about some things.

Now I understand how `_isAuthorized` is useful. And now, with the structured events in place, it seems to me `onUserDataChanged` is just not needed anymore.

Please ask about any other strange things you found. I'll be glad to explain it 😉 👍

**Comment by CesarD** [comment]
@fdcastel how about getting the events I mentioned before?

Unless you already accomplish that with the ones you already introduced in #101?

Like I mentioned before, I'd be interested in knowing when the access token in storage is already expired or not so I can take proper action.
Thanks for your work :)

**Comment by fdcastel** [comment]
@CesarD I'm all in to include every event we deem necessary. Let's talk about them in #79.

**Comment by MovGP0** [comment]
removing `_isAuthorized` was next on my list. seems like this has already been done 👍

**Comment by MovGP0** [comment]
```powershell
git remote add upstream https://github.com/damienbod/angular-auth-oidc-client.git
git fetch upstream
git checkout master
git reset upstream/master --hard
git checkout feature/BRANCHNAME
git rebase master
# rebase and fix conflicts
git push --force

**Comment by fdcastel** [comment]
Working on a new PR now from the latest master. Please disregard this one.

**Pull request closed without merging**
